### ISSUE TITLE
dashes in PELION_DOCKER_PREFIX break the build

### ISSUE THREAD

**Issue by ryannowarm** [PelionIoT/distro-pelion-edge#101]
If you set `PELION_DOCKER_PREFIX` to something that contains a dash, the build breaks with:

    E: Failed to fetch file:/opt/apt-repo/pe-dependencies/Packages  File not found - /opt/apt-repo/pe-dependencies/Packages (2: No such file or directory)
    E: Some index files failed to download. They have been ignored, or old ones used instead.
    Caching golang-14 in local repository
    /pelion-build
    dpkg-buildpackage: info: source package golang-virtual
    dpkg-buildpackage: info: source version 1.14-1
    dpkg-buildpackage: info: source distribution unstable
    dpkg-buildpackage: info: source changed by Krzysztof Bembnista <krzysztof.bembnista@globallogic.com>
    dpkg-buildpackage: info: host architecture amd64
     dpkg-source --before-build .
    dpkg-checkbuilddeps: error: Unmet build dependencies: debhelper (>= 9)
    dpkg-buildpackage: warning: build dependencies/conflicts unsatisfied; aborting
    dpkg-buildpackage: warning: (Use -d flag to override.)
    program finished with exit code 3

This is because we parse the docker image name looking for the distro name by [assuming it's the second field separated by a dash](https://github.com/PelionIoT/linux-pelion-edge/blob/master/build-env/bin/docker-run.sh#L5)

We should either document that you can't use dashes in `PELION_DOCKER_PREFIX` or fix it so you can.

**Comment by ryannowarm** [comment]
Should be fixed in https://github.com/PelionIoT/distro-pelion-edge/pull/131

**Comment by ryannowarm** [comment]
@kbgl , this can be closed now, right?

**Comment by kbgl** [comment]
@ryannowarm yes, it is done
