### ISSUE TITLE
build-all.sh seems to explicitly require the --install flag with --docker flag 

### ISSUE THREAD

**Issue by sameer2209-arm** [PelionIoT/distro-pelion-edge#148]
build.sh script requires explicitly the --install flag when --docker flag is used but the earlier pelion-build-all.sh script seems to set --install flag automatically when the --docker flag was set.

Command being used to build the binaries:
`./build-env/bin/build-all.sh -r --docker=$distroName --arch=$arch`

The builds are failing when being built using the build scripts with --docker flag.

The bionic and buster builds for arm64 and amd64 are giving the following error:
`>> building golang-providers/pe-golang-bin binary package
INFO: Building Debian package!
dpkg-buildpackage: info: source package pe-golang-bin
dpkg-buildpackage: info: source version 1.14-1
dpkg-buildpackage: info: source distribution unstable
dpkg-buildpackage: info: source changed by Krzysztof Bembnista <krzysztof.bembnista@globallogic.com>
dpkg-buildpackage: info: host architecture amd64
 dpkg-source --before-build pe-golang-bin-1.14
dpkg-checkbuilddeps: error: Unmet build dependencies: debhelper (>= 9)
dpkg-buildpackage: warning: build dependencies/conflicts unsatisfied; aborting
dpkg-buildpackage: warning: (Use -d flag to override.)`

And the focal build for amd64 and arm64 is giving the following error:
`HEAD is now at a3c58f2 Merge pull request #29 from ARMmbed/release-4.6.0
INFO: Generating Debian source packages!
mbed-fcc/deb/build.sh: line 59: PYTHONCMD: unbound variable`

**Comment by ryannowarm** [comment]
Hey @kbgl , can you take a look?

**Comment by kbgl** [comment]
> Hey @kbgl , can you take a look?

Should be fixed in #150

**Comment by kbgl** [comment]
@kunal11191 can we also close this issue? It should be fixed now

**Comment by kunal11191** [comment]
@sameer2209-arm can you please confirm and close

**Comment by sameer2209-arm** [comment]
@kunal11191 It is fixed. #150 fixed the issue.
