### ISSUE TITLE
Component build failing on rhel

### ISSUE THREAD

**Issue by kunal11191** [PelionIoT/distro-pelion-edge#165]
@kbgl based on [readme](https://github.com/PelionIoT/distro-pelion-edge#build-single-package-for-red-hat-and-centos ) 
**The build scripts for RPM-based distributions are similar to Debian's:**, when I follow following command sequence build is successful
`
./build-env/bin/docker-run-env.sh bionic ./build-env/bin/build-all.sh --deps --install
./build-env/bin/docker-run-env.sh bionic ./pe-utils/deb/build.sh --install --build --source --arch=amd64
`

but when I try similar commandsfor rhel 
`
./build-env/bin/docker-run-env.sh rhel ./build-env/bin/build-all.sh --deps --install
./build-env/bin/docker-run-env.sh rhel ./pe-utils/rpm/build.sh --install --build --source --arch=amd64
`

it fails with following error
`--arch can be used only with --docker`

also based on our previous conversation 1st positional argument for docker-run-env.sh is equivalent to using --docker flag

**Comment by kbgl** [comment]
This is expected behavior. _RHEL/Centos_ build does not use cross compilation but uses qemu to run arm64 OS images. If host architecture is amd64 you should not pass `--arch` argument here. If you want to run build on different architecture that host using `docker-run-env.sh` you should pass `--arch` switch before selecting target distribution:
```
./build-env/bin/docker-run-env.sh --arch=arm64 rhel ./build-env/bin/build-all.sh --deps --install ./build-env/bin/docker-run-env.sh rhel ./pe-utils/rpm/build.sh --install --build --source
```

I recommend using `--docker` switch in `build-all.sh` (and not using `docker-run-env.sh`) if possible, so you will not have to care about that.

**Comment by kunal11191** [comment]
@kbgl can we somehow give this explanation in readme 

> RHEL/Centos build does not use cross compilation but uses qemu to run arm64 OS images. If host architecture is amd64 you should not pass --arch argument here. If you want to run build on different architecture that host using docker-run-env.sh you should pass --arch switch before selecting target distribution:

or share the command rather than than stating **The build scripts for RPM-based distributions are similar to Debian's**

**Comment by kbgl** [comment]
there is a note in README: 

> When build requires different architecture (when cross-compilation is not available, like for _Red Hat_) `--arch=<architecture>` 
> has to be added to docker-run-env.sh before specifying target environment:
> ```
> ./build-env/bin/docker-run-env.sh --arch arm64 rhel
> ```

**Comment by kunal11191** [comment]
closing this as it is expected behaviour
