### ISSUE TITLE
lintian: command not found

### ISSUE THREAD

**Issue by kunal11191** [PelionIoT/distro-pelion-edge#174]
Steps to Reproduce

- Clone distro pelion-edge
- Copy mbed_cloud_dev_credentials.c and update_default_resources.c
- Run Command **./build-env/bin/build-all.sh --docker=bionic --deps --install --build --source --arch=amd64**

Observation 
all .deb and .lintian filesare generated under /build/deploy/deb/bionic/main/binary-amd64 but bit while verifying following command not found info message is provided
**Update**:- It doesn't cause any failure since error is being logged as info

Error
`>> verifying binary packages for amd64
>> verifying pe-nodejs binary package
INFO: Verifying Debian package!
/pelion-build/pe-nodejs/deb/../../build-env/inc/build-common.sh: line 417: lintian: command not found
>> verifying devicedb binary package
INFO: Verifying Debian package!
/pelion-build/devicedb/deb/../../build-env/inc/build-common.sh: line 417: lintian: command not found
INFO: Done!
>> verifying edge-proxy binary package
INFO: Verifying Debian package!
/pelion-build/edge-proxy/deb/../../build-env/inc/build-common.sh: line 417: lintian: command not found
INFO: Done!
>> verifying global-node-modules binary package
INFO: Verifying Debian package!
/pelion-build/global-node-modules/deb/../../build-env/inc/build-common.sh: line 417: lintian: command not found
INFO: Done!
>> verifying kubelet binary package
buildtype=linux/amd64
INFO: Verifying Debian package!
/pelion-build/kubelet/deb/../../build-env/inc/build-common.sh: line 417: lintian: command not found
INFO: Done!
>> verifying maestro binary package
INFO: Verifying Debian package!
/pelion-build/maestro/deb/../../build-env/inc/build-common.sh: line 417: lintian: command not found
INFO: Done!
>> verifying maestro-shell binary package
INFO: Verifying Debian package!
/pelion-build/maestro-shell/deb/../../build-env/inc/build-common.sh: line 417: lintian: command not found
INFO: Done!
>> verifying mbed-edge-core binary package
INFO: Verifying Debian package!
/pelion-build/mbed-edge-core/deb/../../build-env/inc/build-common.sh: line 417: lintian: command not found
INFO: Done!
>> verifying mbed-edge-core-devmode binary package
INFO: Verifying Debian package!
/pelion-build/mbed-edge-core-devmode/deb/../../build-env/inc/build-common.sh: line 417: lintian: command not found
INFO: Done!
>> verifying golang-github-containernetworking-plugins binary package
INFO: Verifying Debian package!
/pelion-build/golang-github-containernetworking-plugins/deb/../../build-env/inc/build-common.sh: line 417: lintian: command not found
INFO: Done!
>> verifying mbed-edge-examples binary package
INFO: Verifying Debian package!
/pelion-build/mbed-edge-examples/deb/../../build-env/inc/build-common.sh: line 417: lintian: command not found
INFO: Done!
>> verifying mbed-fcc binary package
INFO: Verifying Debian package!
/pelion-build/mbed-fcc/deb/../../build-env/inc/build-common.sh: line 417: lintian: command not found
INFO: Done!
>> verifying pe-utils binary package
INFO: Verifying Debian package!
/pelion-build/pe-utils/deb/../../build-env/inc/build-common.sh: line 417: lintian: command not found
INFO: Done!
>> verifying metapackages using amd64
>> verifying pelion-edge metapackage
INFO: Verifying Debian metapackage!
/pelion-build/metapackages/pelion-edge/deb/../../../build-env/inc/build-common.sh: line 417: lintian: command not found
INFO: Done!
>> verifying pelion-edge-base metapackage
INFO: Verifying Debian metapackage!
/pelion-build/metapackages/pelion-edge-base/deb/../../../build-env/inc/build-common.sh: line 417: lintian: command not found
INFO: Done!
>> verifying pelion-edge-container-orchestration metapackage
INFO: Verifying Debian metapackage!
/pelion-build/metapackages/pelion-edge-container-orchestration/deb/../../../build-env/inc/build-common.sh: line 417: lintian: command not found
INFO: Done!
>> verifying pelion-edge-protocol-engine metapackage
INFO: Verifying Debian metapackage!
/pelion-build/metapackages/pelion-edge-protocol-engine/deb/../../../build-env/inc/build-common.sh: line 417: lintian: command not found
INFO: Done!
>>> build finished <<<`

**Comment by kbgl** [comment]
Currently verification does not stop build script even if it found a problem. Do we want to change it to stop the build on first failed verification or keep as it is @ryannowarm ?

**Comment by ryannowarm** [comment]
@kbgl , I'm fine either way as long as the build script exits non-zero for a failed build.

**Comment by kbgl** [comment]
Fix merged to dev branch.
