### ISSUE TITLE
rpm: add ability to set up a yum repository

### ISSUE THREAD

**Issue by ryannowarm** [PelionIoT/distro-pelion-edge#186]
We have instructions on how to [set up an apt repository](https://github.com/PelionIoT/distro-pelion-edge#apt-repository).  Let's do the same thing for yum

**Comment by ryannowarm** [comment]
@kbgl, here's a high priority issue for you

**Comment by JanneKiiskila** [comment]
https://github.com/PelionIoT/distro-pelion-edge/pull/194 - I believe this PR solves this issue.
