### ISSUE TITLE
bionic, buster and focal tar builds are failing

### ISSUE THREAD

**Issue by sameer2209-arm** [PelionIoT/distro-pelion-edge#199]
bionic, buster and focal tar build are failing on the dev branch of distro-pelion-edge with the following error:
`Applying patches...
Applying patch patches/sethostname.patch
patching file usr/bin/generate-identity.sh
Hunk #1 FAILED at 57.
1 out of 1 hunk FAILED -- rejects in file usr/bin/generate-identity.sh
Patch patches/sethostname.patch does not apply (enforce with -f)`

**Comment by ryannowarm** [comment]
Confirmed: https://github.com/PelionIoT/distro-pelion-edge/runs/3317010639

**Comment by ryannowarm** [comment]
This is fixed now... closing.
