### ISSUE TITLE
buster builds failure due to python unmet dependencies

### ISSUE THREAD

**Issue by sameer2209-arm** [PelionIoT/distro-pelion-edge#205]
buster builds are failing on amd64, arm64, and armhf architectures due to unmet dependencies issue. I was able to reproduce the issue outside the CI infra also on an office machine. 

Logs from the CI build failure:
`The following packages have unmet dependencies:
 python : PreDepends: python-minimal (= 2.7.16-1) but it is not going to be installed
          Depends: libpython-stdlib (= 2.7.16-1) but it is not going to be installed
          Depends: python2 (= 2.7.16-1) but 2.7.18-2 is to be installed
[91mE: Unable to correct problems, you have held broken packages.
[0mThe command '/bin/sh -c apt-get update && apt-get install -y --no-install-recommends 		apt-rdepends 		git 		lintian 		python 		quilt 		ssh 		vim' returned a non-zero code: 100
`

**Comment by ryannowarm** [comment]
Fixed
